module.exports = {

    PORT: 9000,

    WIDTH: 800,

    HEIGHT: 600,

    CHECKPOINT_RADIUS: 60,

    CHECKPOINT_DELAY: 5000,

    TANK_DEFAULT_COLOR:'brown',

    TANK_DEFAULT_CENTER_X:400.0,
    TANK_DEFAULT_CENTER_Y:300.0,

    TANK_THETA: 0.0,
    TANK_DTHETA: 1.0,

    TANK_SPEED: 1.75,

    TANK_HEALTH: 100,
    TANK_MAX_HEALTH: 100,
    TANK_DAMAGE: 5,

    TANK_WIDTH:40.0,
    TANK_HEIGHT: 20.0,
    
    TANK_RELOAD_TIME: 1000.0,

    TURRET_DEFAULT_COLOR:'green',

    TURRET_WIDTH: 20,
    TURRET_HEIGHT: 20,

    BULLET_SPEED: 1.2,
    BULLET_WIDTH: 5,
    BULLET_HEIGHT: 5,
    
    BULLET_DEFAULT_COLOR:'red',
    
}